# Generated by Django 5.1.5 on 2025-04-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0002_alter_voter_apartment_num_alter_voter_party"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="precinct_num",
            field=models.CharField(max_length=2),
        ),
    ]
