# Generated by Django 5.2 on 2025-04-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='category',
            field=models.CharField(choices=[('hat', 'Hat'), ('jacket', 'Jacket'), ('shirt', 'Shirt'), ('bottom', 'Bottom'), ('shoes', 'Shoes')], max_length=20),
        ),
    ]
