# Generated by Django 5.2 on 2025-04-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_clothingitem_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='occasion',
            field=models.CharField(blank=True, choices=[('casual', 'Casual'), ('formal', 'Formal'), ('party', 'Party'), ('work', 'Work'), ('vacation', 'Vacation')], max_length=20),
        ),
        migrations.AddField(
            model_name='outfit',
            name='season',
            field=models.CharField(blank=True, choices=[('fall_winter', 'Fall/Winter'), ('spring_summer', 'Spring/Summer'), ('all_year', 'All Year')], max_length=20),
        ),
    ]
