# Generated by Django 5.2 on 2025-05-01 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_friendship_from_user_alter_friendship_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='outfit',
        ),
    ]
