# Generated by Django 5.2 on 2025-05-01 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_remove_event_outfit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='outfit',
        ),
    ]
