# Generated by Django 5.2 on 2025-05-01 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_remove_rsvp_outfit'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.event'),
        ),
    ]
