# Generated by Django 5.1.5 on 2025-03-02 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mini_fb", "0002_statusmessage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="statusmessage",
            old_name="published",
            new_name="timestamp",
        ),
    ]
