# Generated by Django 5.1.5 on 2025-03-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_fb", "0003_rename_published_statusmessage_timestamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="profile_img_url",
        ),
        migrations.AddField(
            model_name="profile",
            name="image_file",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
