# Generated by Django 5.1.5 on 2025-03-04 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_fb", "0005_image_statusimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statusimage",
            name="profile",
        ),
        migrations.AddField(
            model_name="image",
            name="image_file",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="statusimage",
            name="image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mini_fb.image",
            ),
        ),
    ]
